checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    paths: ['kytos/*', 'tests/*']
    excluded_paths:
        - 'kytos/web-ui/*'
build:
    environment:
        python: 3.6.0
        postgresql: false
        redis: false
    dependencies:
        before:
            - pip install coverage git+git://github.com/diraol/watchdog.git#egg=watchdog
            - pip install git+git://github.com/kytos/python-openflow.git git+git://github.com/kytos/kytos-utils.git
    tests:
        override:
            -
                command: 'tox'
                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'
